### ISSUE TITLE
Documentação - Requisitos não funcionais sem conteúdo coerente

### ISSUE THREAD

**Issue by vitorssoares7** [vitorssoares7/CC8550-Projeto-SimulacaoTestesDeSoftware#2]
A tabela de requisitos não funcionais possui apenas uma linha com os valores "E1-101 -> jklç" . Necessário o detalhamento correto dos requisitos.

**Comment by brigide** [comment]
Resolvido, tabela de RNF escolhida está mais completa e coerente
